//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRDbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ConveyanceCost
    {
        public long ID { get; set; }
        public string EmployeeCode { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string FromLocation { get; set; }
        public string ToLocation { get; set; }
        public Nullable<double> CNG { get; set; }
        public Nullable<double> Car { get; set; }
        public Nullable<double> TaxiCab { get; set; }
        public Nullable<double> Rickshaw { get; set; }
        public Nullable<double> Bus { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public string EmployeeComment { get; set; }
        public string FinanceApproval { get; set; }
        public string FinanceComment { get; set; }
        public string FinanceApprovedBy { get; set; }
        public string ManagementApproval { get; set; }
        public string ManagementComment { get; set; }
        public string ManagementApprovalBy { get; set; }
        public string AttachedFileName { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    }
}
