//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRDbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LeaveStatistics_Employee
    {
        public string StatisticsCode { get; set; }
        public int StatisticsId { get; set; }
        public string EmployeeCode { get; set; }
        public string LeaveCode { get; set; }
        public int AllocatedDays { get; set; }
        public double SpentDays { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public int ModifyCount { get; set; }
        public System.DateTime LastUpdate { get; set; }
    
        public virtual tbl_Employees tbl_Employees { get; set; }
        public virtual tbl_LeaveDefinition tbl_LeaveDefinition { get; set; }
    }
}
