//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRDbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Device_Log_live
    {
        public string AccessID { get; set; }
        public int AccessSerial { get; set; }
        public string AttendanceID { get; set; }
        public string DeviceID { get; set; }
        public Nullable<System.DateTime> AccessDate { get; set; }
        public System.TimeSpan AccessTime { get; set; }
        public System.DateTime LogDate { get; set; }
    }
}
