//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRDbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Leave_Applications
    {
        public string ApplicationCode { get; set; }
        public int ApplicationId { get; set; }
        public string EmployeeCode { get; set; }
        public string LeaveCode { get; set; }
        public string DeptCode { get; set; }
        public System.DateTime LeaveFrom { get; set; }
        public System.DateTime LeaveTill { get; set; }
        public string ApplicantComment { get; set; }
        public string SupportingDocZip { get; set; }
        public string InsuranceCalimPDF { get; set; }
        public string ResponsiblePersons { get; set; }
        public string SupervisorApproval { get; set; }
        public string SupervisorComment { get; set; }
        public string DirectorApproval { get; set; }
        public string DirectorComment { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public int ModifyCount { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public Nullable<bool> isHalf { get; set; }
    
        public virtual tbl_Dept_VU tbl_Dept_VU { get; set; }
        public virtual tbl_Employees tbl_Employees { get; set; }
        public virtual tbl_LeaveDefinition tbl_LeaveDefinition { get; set; }
    }
}
