//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRDbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TimeRules
    {
        public int ID { get; set; }
        public string Days { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public System.TimeSpan LateTime { get; set; }
        public System.TimeSpan EarlyTime { get; set; }
        public string DeptCode { get; set; }
        public System.DateTime TimeStamp { get; set; }
    }
}
