//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRDbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Hrholiday
    {
        public long ID { get; set; }
        public System.DateTime Date { get; set; }
        public bool isHoliday { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    }
}
