//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRDbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LeaveDefinition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_LeaveDefinition()
        {
            this.tbl_Leave_Applications = new HashSet<tbl_Leave_Applications>();
            this.tbl_LeaveStatistics_Employee = new HashSet<tbl_LeaveStatistics_Employee>();
        }
    
        public string LeaveCode { get; set; }
        public int LeaveId { get; set; }
        public string LeaveName { get; set; }
        public string LeaveDescription { get; set; }
        public string LeavePreNoticeNeed { get; set; }
        public string LeaveSuportedDocNeed { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public int ModifyCount { get; set; }
        public System.DateTime LastUpdate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Leave_Applications> tbl_Leave_Applications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LeaveStatistics_Employee> tbl_LeaveStatistics_Employee { get; set; }
    }
}
