//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRDbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Attendance
    {
        public int No { get; set; }
        public string Name { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<System.TimeSpan> OnDuty { get; set; }
        public Nullable<System.TimeSpan> OffDuty { get; set; }
        public Nullable<System.TimeSpan> ClockIn { get; set; }
        public Nullable<System.TimeSpan> ClockOut { get; set; }
        public Nullable<System.TimeSpan> Late { get; set; }
        public Nullable<System.TimeSpan> Early { get; set; }
        public string Absent { get; set; }
        public string Department { get; set; }
    }
}
