//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRDbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Salary_info
    {
        public string SalaryCode { get; set; }
        public int SalaryId { get; set; }
        public string EmployeeCode { get; set; }
        public string GrossSalary { get; set; }
        public string Bonus { get; set; }
        public string Adjustment1 { get; set; }
        public string Adjustment2 { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public int ModifyCount { get; set; }
        public System.DateTime LastUpdate { get; set; }
    
        public virtual tbl_Employees tbl_Employees { get; set; }
    }
}
