//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRDbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_4
    {
        public string Expr1 { get; set; }
        public string LeaveName { get; set; }
        public int AllocatedDays { get; set; }
        public int SpentDays { get; set; }
    }
}
