//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRDbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_6a
    {
        public string EmployeeCode { get; set; }
        public int EmployeeID { get; set; }
        public string UserCode { get; set; }
        public string AttendanceID { get; set; }
        public string Name { get; set; }
        public string DeptName { get; set; }
    }
}
